backend:
  name: github
  repo: thomaslammen/boomchick
  branch: main
media_folder: static/media
public_folder: /media
site_url: https://boomchickcollective.netlify.app
collections:
  - name: paginas
    label: Pagina's
    editor:
      preview: false
    label_singular: Pagina
    files:
      - label: "Homepage"
        name: "home"
        file: "content/homepage.md" # TODO: index.md after release
        media_folder: "static/media/carrousel"
        public_folder: "/media/carrousel"
        fields:
          - { label: "Titel", name: "title", widget: "string" }
          - { label: "Slogan", name: "slogan", widget: "markdown" }

      - label: "Over Ons"
        name: "over-ons"
        file: "content/over-ons.md"
        fields:
          - { label: "Titel", name: "title", widget: "string" }
          - { label: "Tekst", name: "body", widget: "markdown" }

      - label: "Contact"
        name: "contact"
        file: "content/contact.md"
        fields:
          - { label: "Titel", name: "title", widget: "string" }
          - { label: "Tekst", name: "body", widget: "markdown" }

      - label: "Bedankt"
        name: "thanks"
        file: "content/thanks.md"
        fields:
          - { label: "Titel", name: "title", widget: "string" }
          - { label: "Tekst", name: "body", widget: "markdown" }
          - label: "Parameters"
            name: "params"
            widget: "object"
            fields:
              - label: "Thema's"
                name: "themes"
                widget: "list"
                fields:
                  - { label: "Themanaam", name: "name", widget: "string" }
                  - { label: "Spotify ID", name: "spotify", widget: "string" }
                  - { label: "Video", name: "video", widget: "image", required: false }

  - name: overig
    label: Overig
    editor:
      preview: false
    files:
      - label: "Navigatiebalk"
        name: "navigation"
        file: "data/nav.yml"
        fields:
          - label: "Navigation"
            name: "nav"
            widget: "list"
            fields:
              - { label: "Naam", name: "name", widget: "string" }
              - { label: "Pagin URL (bijv. /over-ons/)", name: "page", widget: "string" }

      - label: "Footer"
        name: "footer"
        file: "data/footer.yml"
        fields:
          - label: "Linker blok"
            name: "left"
            widget: "object"
            fields:
              - { label: "Koptekst", name: "title", widget: "string" }
              - label: "Regels"
                name: "lines"
                widget: "list"
                field: { label: "Regeltekst", name: "line", widget: "string" }

          - label: "Middelste blok"
            name: "middle"
            widget: "object"
            fields:
              - { label: "Koptekst", name: "title", widget: "string" }
